apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal-container
        image: dbicho/projpeci:flask-portal-image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
spec:
  selector:
    app: portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort